#############################################################################
# Makefile for building: DuplicateFiles
# Generated by qmake (3.0) (Qt 5.0.2) on: wt. maj 28 16:42:58 2013
# Project:  DuplicateFiles.pro
# Template: app
# Command: /usr/local/bin/qmake -o Makefile DuplicateFiles.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/local/Qt-5.0.2/mkspecs/linux-g++ -I. -I/usr/local/Qt-5.0.2/include -I/usr/local/Qt-5.0.2/include/QtWidgets -I/usr/local/Qt-5.0.2/include/QtGui -I/usr/local/Qt-5.0.2/include/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Qt-5.0.2/lib
LIBS          = $(SUBLIBS) -L/usr/local/Qt-5.0.2/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		dpfile.cpp \
		dpdir.cpp \
		utils.cpp \
		taskprogress.cpp \
		taskprogressmanager.cpp \
		mainwindow.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		dpfile.o \
		dpdir.o \
		utils.o \
		taskprogress.o \
		taskprogressmanager.o \
		mainwindow.o \
		moc_mainwindow.o
DIST          = /usr/local/Qt-5.0.2/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.0.2/mkspecs/common/shell-unix.conf \
		/usr/local/Qt-5.0.2/mkspecs/common/unix.conf \
		/usr/local/Qt-5.0.2/mkspecs/common/linux.conf \
		/usr/local/Qt-5.0.2/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.0.2/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.0.2/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.0.2/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.0.2/mkspecs/qconfig.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_bootstrap.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_clucene.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_designercomponents.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_qmldevtools.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_quickparticles.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_v8.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.0.2/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.0.2/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt-5.0.2/mkspecs/features/spec_post.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/unix/default_pre.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/qt.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/resources.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/moc.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/uic.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/wayland-scanner.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/lex.prf \
		DuplicateFiles.pro \
		DuplicateFiles.pro
QMAKE_TARGET  = DuplicateFiles
DESTDIR       = 
TARGET        = DuplicateFiles


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: DuplicateFiles.pro /usr/local/Qt-5.0.2/mkspecs/linux-g++/qmake.conf /usr/local/Qt-5.0.2/mkspecs/features/spec_pre.prf \
		/usr/local/Qt-5.0.2/mkspecs/common/shell-unix.conf \
		/usr/local/Qt-5.0.2/mkspecs/common/unix.conf \
		/usr/local/Qt-5.0.2/mkspecs/common/linux.conf \
		/usr/local/Qt-5.0.2/mkspecs/common/gcc-base.conf \
		/usr/local/Qt-5.0.2/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Qt-5.0.2/mkspecs/common/g++-base.conf \
		/usr/local/Qt-5.0.2/mkspecs/common/g++-unix.conf \
		/usr/local/Qt-5.0.2/mkspecs/qconfig.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_bootstrap.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_clucene.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_core.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_designercomponents.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_help.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_network.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_platformsupport.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_qmldevtools.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_quickparticles.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_script.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_v8.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/Qt-5.0.2/mkspecs/features/qt_functions.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/qt_config.prf \
		/usr/local/Qt-5.0.2/mkspecs/linux-g++/qmake.conf \
		/usr/local/Qt-5.0.2/mkspecs/features/spec_post.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/default_pre.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/unix/default_pre.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/resolve_config.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/default_post.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/warn_on.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/qt.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/resources.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/moc.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/unix/opengl.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/uic.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/unix/thread.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/wayland-scanner.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/testcase_targets.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/exceptions.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/yacc.prf \
		/usr/local/Qt-5.0.2/mkspecs/features/lex.prf \
		DuplicateFiles.pro \
		/usr/local/Qt-5.0.2/lib/libQt5Widgets.prl \
		/usr/local/Qt-5.0.2/lib/libQt5Gui.prl \
		/usr/local/Qt-5.0.2/lib/libQt5Core.prl
	$(QMAKE) -o Makefile DuplicateFiles.pro
/usr/local/Qt-5.0.2/mkspecs/features/spec_pre.prf:
/usr/local/Qt-5.0.2/mkspecs/common/shell-unix.conf:
/usr/local/Qt-5.0.2/mkspecs/common/unix.conf:
/usr/local/Qt-5.0.2/mkspecs/common/linux.conf:
/usr/local/Qt-5.0.2/mkspecs/common/gcc-base.conf:
/usr/local/Qt-5.0.2/mkspecs/common/gcc-base-unix.conf:
/usr/local/Qt-5.0.2/mkspecs/common/g++-base.conf:
/usr/local/Qt-5.0.2/mkspecs/common/g++-unix.conf:
/usr/local/Qt-5.0.2/mkspecs/qconfig.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_bootstrap.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_clucene.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_core.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_designer.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_designercomponents.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_gui.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_help.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_network.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_platformsupport.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_qml.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_qmldevtools.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_qtmultimediaquicktools.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_quick.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_quickparticles.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_script.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_sql.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_svg.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_v8.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_xml.pri:
/usr/local/Qt-5.0.2/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/Qt-5.0.2/mkspecs/features/qt_functions.prf:
/usr/local/Qt-5.0.2/mkspecs/features/qt_config.prf:
/usr/local/Qt-5.0.2/mkspecs/linux-g++/qmake.conf:
/usr/local/Qt-5.0.2/mkspecs/features/spec_post.prf:
/usr/local/Qt-5.0.2/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt-5.0.2/mkspecs/features/default_pre.prf:
/usr/local/Qt-5.0.2/mkspecs/features/unix/default_pre.prf:
/usr/local/Qt-5.0.2/mkspecs/features/resolve_config.prf:
/usr/local/Qt-5.0.2/mkspecs/features/default_post.prf:
/usr/local/Qt-5.0.2/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Qt-5.0.2/mkspecs/features/warn_on.prf:
/usr/local/Qt-5.0.2/mkspecs/features/qt.prf:
/usr/local/Qt-5.0.2/mkspecs/features/resources.prf:
/usr/local/Qt-5.0.2/mkspecs/features/moc.prf:
/usr/local/Qt-5.0.2/mkspecs/features/unix/opengl.prf:
/usr/local/Qt-5.0.2/mkspecs/features/uic.prf:
/usr/local/Qt-5.0.2/mkspecs/features/unix/thread.prf:
/usr/local/Qt-5.0.2/mkspecs/features/wayland-scanner.prf:
/usr/local/Qt-5.0.2/mkspecs/features/testcase_targets.prf:
/usr/local/Qt-5.0.2/mkspecs/features/exceptions.prf:
/usr/local/Qt-5.0.2/mkspecs/features/yacc.prf:
/usr/local/Qt-5.0.2/mkspecs/features/lex.prf:
DuplicateFiles.pro:
/usr/local/Qt-5.0.2/lib/libQt5Widgets.prl:
/usr/local/Qt-5.0.2/lib/libQt5Gui.prl:
/usr/local/Qt-5.0.2/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile DuplicateFiles.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/DuplicateFiles1.0.0 || mkdir -p .tmp/DuplicateFiles1.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/DuplicateFiles1.0.0/ && $(COPY_FILE) --parents dpfile.h dpdir.h err.h utils.h taskprogress.h taskprogressmanager.h mainwindow.h .tmp/DuplicateFiles1.0.0/ && $(COPY_FILE) --parents main.cpp dpfile.cpp dpdir.cpp utils.cpp taskprogress.cpp taskprogressmanager.cpp mainwindow.cpp .tmp/DuplicateFiles1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/DuplicateFiles1.0.0/ && (cd `dirname .tmp/DuplicateFiles1.0.0` && $(TAR) DuplicateFiles1.0.0.tar DuplicateFiles1.0.0 && $(COMPRESS) DuplicateFiles1.0.0.tar) && $(MOVE) `dirname .tmp/DuplicateFiles1.0.0`/DuplicateFiles1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/DuplicateFiles1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_wayland-server-header_make_all:
compiler_wayland-server-header_clean:
compiler_wayland-client-header_make_all:
compiler_wayland-client-header_clean:
compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: /usr/local/Qt-5.0.2/include/QtWidgets/QMainWindow \
		/usr/local/Qt-5.0.2/include/QtWidgets/qmainwindow.h \
		/usr/local/Qt-5.0.2/include/QtWidgets/qwidget.h \
		/usr/local/Qt-5.0.2/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.0.2/include/QtCore/qglobal.h \
		/usr/local/Qt-5.0.2/include/QtCore/qconfig.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlogging.h \
		/usr/local/Qt-5.0.2/include/QtCore/qflags.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.0.2/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.0.2/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobject.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstring.h \
		/usr/local/Qt-5.0.2/include/QtCore/qchar.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.0.2/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.0.2/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_integrity.h \
		/usr/local/Qt-5.0.2/include/QtCore/qoldbasicatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_vxworks.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_power.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_alpha.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_bfin.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_s390.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_sh4a.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_sparc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.0.2/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlist.h \
		/usr/local/Qt-5.0.2/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.0.2/include/QtCore/qiterator.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.0.2/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.0.2/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.0.2/include/QtCore/qisenum.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmargins.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.0.2/include/QtCore/qrect.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsize.h \
		/usr/local/Qt-5.0.2/include/QtCore/qpoint.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpalette.h \
		/usr/local/Qt-5.0.2/include/QtGui/qcolor.h \
		/usr/local/Qt-5.0.2/include/QtGui/qrgb.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.0.2/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.0.2/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.0.2/include/QtCore/qpair.h \
		/usr/local/Qt-5.0.2/include/QtCore/qregexp.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.0.2/include/QtGui/qbrush.h \
		/usr/local/Qt-5.0.2/include/QtCore/qvector.h \
		/usr/local/Qt-5.0.2/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.0.2/include/QtGui/qregion.h \
		/usr/local/Qt-5.0.2/include/QtCore/qline.h \
		/usr/local/Qt-5.0.2/include/QtGui/qtransform.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.0.2/include/QtGui/qimage.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qhash.h \
		/usr/local/Qt-5.0.2/include/QtGui/qfont.h \
		/usr/local/Qt-5.0.2/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.0.2/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.0.2/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-5.0.2/include/QtGui/qcursor.h \
		/usr/local/Qt-5.0.2/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.0.2/include/QtGui/qevent.h \
		/usr/local/Qt-5.0.2/include/QtCore/qvariant.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmap.h \
		/usr/local/Qt-5.0.2/include/QtCore/qdebug.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlocale.h \
		/usr/local/Qt-5.0.2/include/QtCore/qset.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.0.2/include/QtCore/qurl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfile.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.0.2/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.0.2/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-5.0.2/include/QtWidgets/qtabwidget.h \
		/usr/local/Qt-5.0.2/include/QtGui/qicon.h \
		mainwindow.h
	/usr/local/Qt-5.0.2/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

compiler_wayland-code_make_all:
compiler_wayland-code_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/local/Qt-5.0.2/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		/usr/local/Qt-5.0.2/include/QtWidgets/QMainWindow \
		/usr/local/Qt-5.0.2/include/QtWidgets/qmainwindow.h \
		/usr/local/Qt-5.0.2/include/QtWidgets/qwidget.h \
		/usr/local/Qt-5.0.2/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.0.2/include/QtCore/qglobal.h \
		/usr/local/Qt-5.0.2/include/QtCore/qconfig.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlogging.h \
		/usr/local/Qt-5.0.2/include/QtCore/qflags.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.0.2/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.0.2/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobject.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstring.h \
		/usr/local/Qt-5.0.2/include/QtCore/qchar.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.0.2/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.0.2/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_integrity.h \
		/usr/local/Qt-5.0.2/include/QtCore/qoldbasicatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_vxworks.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_power.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_alpha.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_bfin.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_s390.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_sh4a.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_sparc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.0.2/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlist.h \
		/usr/local/Qt-5.0.2/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.0.2/include/QtCore/qiterator.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.0.2/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.0.2/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.0.2/include/QtCore/qisenum.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmargins.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.0.2/include/QtCore/qrect.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsize.h \
		/usr/local/Qt-5.0.2/include/QtCore/qpoint.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpalette.h \
		/usr/local/Qt-5.0.2/include/QtGui/qcolor.h \
		/usr/local/Qt-5.0.2/include/QtGui/qrgb.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.0.2/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.0.2/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.0.2/include/QtCore/qpair.h \
		/usr/local/Qt-5.0.2/include/QtCore/qregexp.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.0.2/include/QtGui/qbrush.h \
		/usr/local/Qt-5.0.2/include/QtCore/qvector.h \
		/usr/local/Qt-5.0.2/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.0.2/include/QtGui/qregion.h \
		/usr/local/Qt-5.0.2/include/QtCore/qline.h \
		/usr/local/Qt-5.0.2/include/QtGui/qtransform.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.0.2/include/QtGui/qimage.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qhash.h \
		/usr/local/Qt-5.0.2/include/QtGui/qfont.h \
		/usr/local/Qt-5.0.2/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.0.2/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.0.2/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-5.0.2/include/QtGui/qcursor.h \
		/usr/local/Qt-5.0.2/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.0.2/include/QtGui/qevent.h \
		/usr/local/Qt-5.0.2/include/QtCore/qvariant.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmap.h \
		/usr/local/Qt-5.0.2/include/QtCore/qdebug.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlocale.h \
		/usr/local/Qt-5.0.2/include/QtCore/qset.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.0.2/include/QtCore/qurl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfile.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.0.2/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.0.2/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-5.0.2/include/QtWidgets/qtabwidget.h \
		/usr/local/Qt-5.0.2/include/QtGui/qicon.h \
		/usr/local/Qt-5.0.2/include/QtWidgets/QApplication \
		/usr/local/Qt-5.0.2/include/QtWidgets/qapplication.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-5.0.2/include/QtCore/qeventloop.h \
		/usr/local/Qt-5.0.2/include/QtWidgets/qdesktopwidget.h \
		/usr/local/Qt-5.0.2/include/QtGui/qguiapplication.h \
		/usr/local/Qt-5.0.2/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

dpfile.o: dpfile.cpp dpfile.h \
		/usr/local/Qt-5.0.2/include/QtCore/QString \
		/usr/local/Qt-5.0.2/include/QtCore/qstring.h \
		/usr/local/Qt-5.0.2/include/QtCore/qchar.h \
		/usr/local/Qt-5.0.2/include/QtCore/qglobal.h \
		/usr/local/Qt-5.0.2/include/QtCore/qconfig.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlogging.h \
		/usr/local/Qt-5.0.2/include/QtCore/qflags.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.0.2/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.0.2/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_integrity.h \
		/usr/local/Qt-5.0.2/include/QtCore/qoldbasicatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_vxworks.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_power.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_alpha.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_bfin.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_s390.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_sh4a.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_sparc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.0.2/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.0.2/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.0.2/include/QtCore/QDateTime \
		/usr/local/Qt-5.0.2/include/QtCore/qdatetime.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobject.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlist.h \
		/usr/local/Qt-5.0.2/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.0.2/include/QtCore/qiterator.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.0.2/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.0.2/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.0.2/include/QtCore/qisenum.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qhash.h \
		/usr/local/Qt-5.0.2/include/QtCore/qpair.h \
		/usr/local/Qt-5.0.2/include/QtCore/QCryptographicHash \
		/usr/local/Qt-5.0.2/include/QtCore/qcryptographichash.h \
		taskprogressmanager.h \
		err.h \
		/usr/local/Qt-5.0.2/include/QtCore/QException \
		/usr/local/Qt-5.0.2/include/QtCore/qexception.h \
		utils.h \
		taskprogress.h \
		/usr/local/Qt-5.0.2/include/QtCore/QFile \
		/usr/local/Qt-5.0.2/include/QtCore/qfile.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.0.2/include/QtCore/qiodevice.h \
		dpdir.h \
		/usr/local/Qt-5.0.2/include/QtCore/QDir \
		/usr/local/Qt-5.0.2/include/QtCore/qdir.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfileinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.0.2/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.0.2/include/QtCore/qregexp.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.0.2/include/QtCore/QSet \
		/usr/local/Qt-5.0.2/include/QtCore/qset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dpfile.o dpfile.cpp

dpdir.o: dpdir.cpp dpdir.h \
		/usr/local/Qt-5.0.2/include/QtCore/QDir \
		/usr/local/Qt-5.0.2/include/QtCore/qdir.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstring.h \
		/usr/local/Qt-5.0.2/include/QtCore/qchar.h \
		/usr/local/Qt-5.0.2/include/QtCore/qglobal.h \
		/usr/local/Qt-5.0.2/include/QtCore/qconfig.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlogging.h \
		/usr/local/Qt-5.0.2/include/QtCore/qflags.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.0.2/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.0.2/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_integrity.h \
		/usr/local/Qt-5.0.2/include/QtCore/qoldbasicatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_vxworks.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_power.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_alpha.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_bfin.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_s390.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_sh4a.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_sparc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.0.2/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.0.2/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfileinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfile.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.0.2/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobject.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlist.h \
		/usr/local/Qt-5.0.2/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.0.2/include/QtCore/qiterator.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.0.2/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.0.2/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.0.2/include/QtCore/qisenum.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.0.2/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.0.2/include/QtCore/qpair.h \
		/usr/local/Qt-5.0.2/include/QtCore/qregexp.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.0.2/include/QtCore/QSet \
		/usr/local/Qt-5.0.2/include/QtCore/qset.h \
		/usr/local/Qt-5.0.2/include/QtCore/qhash.h \
		dpfile.h \
		/usr/local/Qt-5.0.2/include/QtCore/QString \
		/usr/local/Qt-5.0.2/include/QtCore/QDateTime \
		/usr/local/Qt-5.0.2/include/QtCore/qdatetime.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/QCryptographicHash \
		/usr/local/Qt-5.0.2/include/QtCore/qcryptographichash.h \
		taskprogressmanager.h \
		taskprogress.h \
		/usr/local/Qt-5.0.2/include/QtCore/QFileInfoList
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dpdir.o dpdir.cpp

utils.o: utils.cpp utils.h \
		/usr/local/Qt-5.0.2/include/QtCore/QString \
		/usr/local/Qt-5.0.2/include/QtCore/qstring.h \
		/usr/local/Qt-5.0.2/include/QtCore/qchar.h \
		/usr/local/Qt-5.0.2/include/QtCore/qglobal.h \
		/usr/local/Qt-5.0.2/include/QtCore/qconfig.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlogging.h \
		/usr/local/Qt-5.0.2/include/QtCore/qflags.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.0.2/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.0.2/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_integrity.h \
		/usr/local/Qt-5.0.2/include/QtCore/qoldbasicatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_vxworks.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_power.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_alpha.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_bfin.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_s390.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_sh4a.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_sparc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.0.2/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.0.2/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringbuilder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o utils.cpp

taskprogress.o: taskprogress.cpp taskprogress.h \
		/usr/local/Qt-5.0.2/include/QtCore/QString \
		/usr/local/Qt-5.0.2/include/QtCore/qstring.h \
		/usr/local/Qt-5.0.2/include/QtCore/qchar.h \
		/usr/local/Qt-5.0.2/include/QtCore/qglobal.h \
		/usr/local/Qt-5.0.2/include/QtCore/qconfig.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlogging.h \
		/usr/local/Qt-5.0.2/include/QtCore/qflags.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.0.2/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.0.2/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_integrity.h \
		/usr/local/Qt-5.0.2/include/QtCore/qoldbasicatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_vxworks.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_power.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_alpha.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_bfin.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_s390.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_sh4a.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_sparc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.0.2/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.0.2/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.0.2/include/QtCore/QDateTime \
		/usr/local/Qt-5.0.2/include/QtCore/qdatetime.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobject.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlist.h \
		/usr/local/Qt-5.0.2/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.0.2/include/QtCore/qiterator.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.0.2/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.0.2/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.0.2/include/QtCore/qisenum.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qhash.h \
		/usr/local/Qt-5.0.2/include/QtCore/qpair.h \
		taskprogressmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskprogress.o taskprogress.cpp

taskprogressmanager.o: taskprogressmanager.cpp taskprogressmanager.h \
		/usr/local/Qt-5.0.2/include/QtCore/QDateTime \
		/usr/local/Qt-5.0.2/include/QtCore/qdatetime.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstring.h \
		/usr/local/Qt-5.0.2/include/QtCore/qchar.h \
		/usr/local/Qt-5.0.2/include/QtCore/qglobal.h \
		/usr/local/Qt-5.0.2/include/QtCore/qconfig.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlogging.h \
		/usr/local/Qt-5.0.2/include/QtCore/qflags.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.0.2/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.0.2/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_integrity.h \
		/usr/local/Qt-5.0.2/include/QtCore/qoldbasicatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_vxworks.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_power.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_alpha.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_bfin.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_s390.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_sh4a.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_sparc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.0.2/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.0.2/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobject.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlist.h \
		/usr/local/Qt-5.0.2/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.0.2/include/QtCore/qiterator.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.0.2/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.0.2/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.0.2/include/QtCore/qisenum.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qhash.h \
		/usr/local/Qt-5.0.2/include/QtCore/qpair.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taskprogressmanager.o taskprogressmanager.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		/usr/local/Qt-5.0.2/include/QtWidgets/QMainWindow \
		/usr/local/Qt-5.0.2/include/QtWidgets/qmainwindow.h \
		/usr/local/Qt-5.0.2/include/QtWidgets/qwidget.h \
		/usr/local/Qt-5.0.2/include/QtGui/qwindowdefs.h \
		/usr/local/Qt-5.0.2/include/QtCore/qglobal.h \
		/usr/local/Qt-5.0.2/include/QtCore/qconfig.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfeatures.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsystemdetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcompilerdetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qprocessordetection.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlogging.h \
		/usr/local/Qt-5.0.2/include/QtCore/qflags.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtypeinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtypetraits.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsysinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobjectdefs.h \
		/usr/local/Qt-5.0.2/include/QtCore/qnamespace.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobjectdefs_impl.h \
		/usr/local/Qt-5.0.2/include/QtGui/qwindowdefs_win.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobject.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstring.h \
		/usr/local/Qt-5.0.2/include/QtCore/qchar.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbytearray.h \
		/usr/local/Qt-5.0.2/include/QtCore/qrefcount.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbasicatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_bootstrap.h \
		/usr/local/Qt-5.0.2/include/QtCore/qgenericatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_msvc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_integrity.h \
		/usr/local/Qt-5.0.2/include/QtCore/qoldbasicatomic.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_vxworks.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_power.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_alpha.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv7.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv6.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_armv5.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_bfin.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_ia64.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_mips.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_s390.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_sh4a.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_sparc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_x86.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_cxx11.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_gcc.h \
		/usr/local/Qt-5.0.2/include/QtCore/qatomic_unix.h \
		/usr/local/Qt-5.0.2/include/QtCore/qarraydata.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringbuilder.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlist.h \
		/usr/local/Qt-5.0.2/include/QtCore/qalgorithms.h \
		/usr/local/Qt-5.0.2/include/QtCore/qiterator.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcoreevent.h \
		/usr/local/Qt-5.0.2/include/QtCore/qscopedpointer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmetatype.h \
		/usr/local/Qt-5.0.2/include/QtCore/qvarlengtharray.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcontainerfwd.h \
		/usr/local/Qt-5.0.2/include/QtCore/qisenum.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobject_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmargins.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpaintdevice.h \
		/usr/local/Qt-5.0.2/include/QtCore/qrect.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsize.h \
		/usr/local/Qt-5.0.2/include/QtCore/qpoint.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpalette.h \
		/usr/local/Qt-5.0.2/include/QtGui/qcolor.h \
		/usr/local/Qt-5.0.2/include/QtGui/qrgb.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringlist.h \
		/usr/local/Qt-5.0.2/include/QtCore/qdatastream.h \
		/usr/local/Qt-5.0.2/include/QtCore/qiodevice.h \
		/usr/local/Qt-5.0.2/include/QtCore/qpair.h \
		/usr/local/Qt-5.0.2/include/QtCore/qregexp.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringmatcher.h \
		/usr/local/Qt-5.0.2/include/QtGui/qbrush.h \
		/usr/local/Qt-5.0.2/include/QtCore/qvector.h \
		/usr/local/Qt-5.0.2/include/QtGui/qmatrix.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpolygon.h \
		/usr/local/Qt-5.0.2/include/QtGui/qregion.h \
		/usr/local/Qt-5.0.2/include/QtCore/qline.h \
		/usr/local/Qt-5.0.2/include/QtGui/qtransform.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpainterpath.h \
		/usr/local/Qt-5.0.2/include/QtGui/qimage.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpixmap.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsharedpointer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qshareddata.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsharedpointer_impl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qhash.h \
		/usr/local/Qt-5.0.2/include/QtGui/qfont.h \
		/usr/local/Qt-5.0.2/include/QtGui/qfontmetrics.h \
		/usr/local/Qt-5.0.2/include/QtGui/qfontinfo.h \
		/usr/local/Qt-5.0.2/include/QtWidgets/qsizepolicy.h \
		/usr/local/Qt-5.0.2/include/QtGui/qcursor.h \
		/usr/local/Qt-5.0.2/include/QtGui/qkeysequence.h \
		/usr/local/Qt-5.0.2/include/QtGui/qevent.h \
		/usr/local/Qt-5.0.2/include/QtCore/qvariant.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmap.h \
		/usr/local/Qt-5.0.2/include/QtCore/qdebug.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtextstream.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlocale.h \
		/usr/local/Qt-5.0.2/include/QtCore/qset.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcontiguouscache.h \
		/usr/local/Qt-5.0.2/include/QtCore/qurl.h \
		/usr/local/Qt-5.0.2/include/QtCore/qurlquery.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfile.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfiledevice.h \
		/usr/local/Qt-5.0.2/include/QtGui/qvector2d.h \
		/usr/local/Qt-5.0.2/include/QtGui/qtouchdevice.h \
		/usr/local/Qt-5.0.2/include/QtWidgets/qtabwidget.h \
		/usr/local/Qt-5.0.2/include/QtGui/qicon.h \
		ui_mainwindow.h \
		/usr/local/Qt-5.0.2/include/QtCore/QVariant \
		/usr/local/Qt-5.0.2/include/QtGui/QtGui \
		/usr/local/Qt-5.0.2/include/QtCore/QtCore \
		/usr/local/Qt-5.0.2/include/QtCore/qabstractanimation.h \
		/usr/local/Qt-5.0.2/include/QtCore/qanimationgroup.h \
		/usr/local/Qt-5.0.2/include/QtCore/qparallelanimationgroup.h \
		/usr/local/Qt-5.0.2/include/QtCore/qpauseanimation.h \
		/usr/local/Qt-5.0.2/include/QtCore/qpropertyanimation.h \
		/usr/local/Qt-5.0.2/include/QtCore/qvariantanimation.h \
		/usr/local/Qt-5.0.2/include/QtCore/qeasingcurve.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsequentialanimationgroup.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtextcodec.h \
		/usr/local/Qt-5.0.2/include/QtCore/qendian.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlibraryinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qdatetime.h \
		/usr/local/Qt-5.0.2/include/QtCore/qnumeric.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbuffer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qdir.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfileinfo.h \
		/usr/local/Qt-5.0.2/include/QtCore/qdiriterator.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfilesystemwatcher.h \
		/usr/local/Qt-5.0.2/include/QtCore/qprocess.h \
		/usr/local/Qt-5.0.2/include/QtCore/qresource.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsettings.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstandardpaths.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtemporarydir.h \
		/usr/local/Qt-5.0.2/include/QtCore/QScopedPointer \
		/usr/local/Qt-5.0.2/include/QtCore/qtemporaryfile.h \
		/usr/local/Qt-5.0.2/include/QtCore/qabstractitemmodel.h \
		/usr/local/Qt-5.0.2/include/QtCore/qabstractproxymodel.h \
		/usr/local/Qt-5.0.2/include/QtCore/qidentityproxymodel.h \
		/usr/local/Qt-5.0.2/include/QtCore/qitemselectionmodel.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsortfilterproxymodel.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstringlistmodel.h \
		/usr/local/Qt-5.0.2/include/QtCore/qjsonarray.h \
		/usr/local/Qt-5.0.2/include/QtCore/qjsonvalue.h \
		/usr/local/Qt-5.0.2/include/QtCore/qjsondocument.h \
		/usr/local/Qt-5.0.2/include/QtCore/qjsonobject.h \
		/usr/local/Qt-5.0.2/include/QtCore/qabstracteventdispatcher.h \
		/usr/local/Qt-5.0.2/include/QtCore/qeventloop.h \
		/usr/local/Qt-5.0.2/include/QtCore/qabstractnativeeventfilter.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbasictimer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcoreapplication.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmath.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmetaobject.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmimedata.h \
		/usr/local/Qt-5.0.2/include/QtCore/qobjectcleanuphandler.h \
		/usr/local/Qt-5.0.2/include/QtCore/qpointer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsharedmemory.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsignalmapper.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsocketnotifier.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsystemsemaphore.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtimer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtranslator.h \
		/usr/local/Qt-5.0.2/include/QtCore/qwineventnotifier.h \
		/usr/local/Qt-5.0.2/include/QtCore/qt_windows.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmimedatabase.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmimetype.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfactoryinterface.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlibrary.h \
		/usr/local/Qt-5.0.2/include/QtCore/qplugin.h \
		/usr/local/Qt-5.0.2/include/QtCore/qpluginloader.h \
		/usr/local/Qt-5.0.2/include/QtCore/quuid.h \
		/usr/local/Qt-5.0.2/include/QtCore/qabstractstate.h \
		/usr/local/Qt-5.0.2/include/QtCore/qabstracttransition.h \
		/usr/local/Qt-5.0.2/include/QtCore/qeventtransition.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfinalstate.h \
		/usr/local/Qt-5.0.2/include/QtCore/qhistorystate.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsignaltransition.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstate.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstatemachine.h \
		/usr/local/Qt-5.0.2/include/QtCore/qexception.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfuture.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfutureinterface.h \
		/usr/local/Qt-5.0.2/include/QtCore/qrunnable.h \
		/usr/local/Qt-5.0.2/include/QtCore/qmutex.h \
		/usr/local/Qt-5.0.2/include/QtCore/qresultstore.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfuturesynchronizer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qfuturewatcher.h \
		/usr/local/Qt-5.0.2/include/QtCore/qreadwritelock.h \
		/usr/local/Qt-5.0.2/include/QtCore/qsemaphore.h \
		/usr/local/Qt-5.0.2/include/QtCore/qthread.h \
		/usr/local/Qt-5.0.2/include/QtCore/qthreadpool.h \
		/usr/local/Qt-5.0.2/include/QtCore/qthreadstorage.h \
		/usr/local/Qt-5.0.2/include/QtCore/qwaitcondition.h \
		/usr/local/Qt-5.0.2/include/QtCore/qarraydataops.h \
		/usr/local/Qt-5.0.2/include/QtCore/qarraydatapointer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbitarray.h \
		/usr/local/Qt-5.0.2/include/QtCore/qbytearraymatcher.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcache.h \
		/usr/local/Qt-5.0.2/include/QtCore/qcryptographichash.h \
		/usr/local/Qt-5.0.2/include/QtCore/qelapsedtimer.h \
		/usr/local/Qt-5.0.2/include/QtCore/qlinkedlist.h \
		/usr/local/Qt-5.0.2/include/QtCore/qqueue.h \
		/usr/local/Qt-5.0.2/include/QtCore/qregularexpression.h \
		/usr/local/Qt-5.0.2/include/QtCore/qscopedvaluerollback.h \
		/usr/local/Qt-5.0.2/include/QtCore/qstack.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtextboundaryfinder.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtimeline.h \
		/usr/local/Qt-5.0.2/include/QtCore/qxmlstream.h \
		/usr/local/Qt-5.0.2/include/QtCore/qtcoreversion.h \
		/usr/local/Qt-5.0.2/include/QtGui/qaccessible.h \
		/usr/local/Qt-5.0.2/include/QtGui/qaccessible2.h \
		/usr/local/Qt-5.0.2/include/QtGui/qaccessiblebridge.h \
		/usr/local/Qt-5.0.2/include/QtGui/qaccessibleobject.h \
		/usr/local/Qt-5.0.2/include/QtGui/qaccessibleplugin.h \
		/usr/local/Qt-5.0.2/include/QtGui/qbitmap.h \
		/usr/local/Qt-5.0.2/include/QtGui/qiconengine.h \
		/usr/local/Qt-5.0.2/include/QtGui/qiconengineplugin.h \
		/usr/local/Qt-5.0.2/include/QtGui/qimageiohandler.h \
		/usr/local/Qt-5.0.2/include/QtGui/qimagereader.h \
		/usr/local/Qt-5.0.2/include/QtGui/qimagewriter.h \
		/usr/local/Qt-5.0.2/include/QtGui/qmovie.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpicture.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpictureformatplugin.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpixmapcache.h \
		/usr/local/Qt-5.0.2/include/QtGui/qstandarditemmodel.h \
		/usr/local/Qt-5.0.2/include/QtGui/qclipboard.h \
		/usr/local/Qt-5.0.2/include/QtGui/qdrag.h \
		/usr/local/Qt-5.0.2/include/QtGui/qgenericplugin.h \
		/usr/local/Qt-5.0.2/include/QtGui/qgenericpluginfactory.h \
		/usr/local/Qt-5.0.2/include/QtGui/qguiapplication.h \
		/usr/local/Qt-5.0.2/include/QtGui/qinputmethod.h \
		/usr/local/Qt-5.0.2/include/QtGui/qopenglcontext.h \
		/usr/local/Qt-5.0.2/include/QtCore/QObject \
		/usr/local/Qt-5.0.2/include/QtGui/QSurfaceFormat \
		/usr/local/Qt-5.0.2/include/QtGui/qsurfaceformat.h \
		/usr/local/Qt-5.0.2/include/QtGui/qopengl.h \
		/usr/local/Qt-5.0.2/include/QtGui/qopengles2ext.h \
		/usr/local/Qt-5.0.2/include/QtGui/qopenglext.h \
		/usr/local/Qt-5.0.2/include/QtGui/qscreen.h \
		/usr/local/Qt-5.0.2/include/QtCore/QList \
		/usr/local/Qt-5.0.2/include/QtCore/QRect \
		/usr/local/Qt-5.0.2/include/QtCore/QSize \
		/usr/local/Qt-5.0.2/include/QtCore/QSizeF \
		/usr/local/Qt-5.0.2/include/QtGui/QTransform \
		/usr/local/Qt-5.0.2/include/QtGui/qsessionmanager.h \
		/usr/local/Qt-5.0.2/include/QtGui/qstylehints.h \
		/usr/local/Qt-5.0.2/include/QtGui/qsurface.h \
		/usr/local/Qt-5.0.2/include/QtGui/qwindow.h \
		/usr/local/Qt-5.0.2/include/QtCore/QEvent \
		/usr/local/Qt-5.0.2/include/QtCore/QMargins \
		/usr/local/Qt-5.0.2/include/QtGui/qgenericmatrix.h \
		/usr/local/Qt-5.0.2/include/QtGui/qmatrix4x4.h \
		/usr/local/Qt-5.0.2/include/QtGui/qvector3d.h \
		/usr/local/Qt-5.0.2/include/QtGui/qvector4d.h \
		/usr/local/Qt-5.0.2/include/QtGui/qquaternion.h \
		/usr/local/Qt-5.0.2/include/QtGui/qopenglbuffer.h \
		/usr/local/Qt-5.0.2/include/QtGui/qopenglframebufferobject.h \
		/usr/local/Qt-5.0.2/include/QtGui/qopenglfunctions.h \
		/usr/local/Qt-5.0.2/include/QtGui/qopenglpaintdevice.h \
		/usr/local/Qt-5.0.2/include/QtGui/qopenglshaderprogram.h \
		/usr/local/Qt-5.0.2/include/QtGui/qbackingstore.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpagedpaintdevice.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpaintengine.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpainter.h \
		/usr/local/Qt-5.0.2/include/QtGui/qtextoption.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpen.h \
		/usr/local/Qt-5.0.2/include/QtGui/qpdfwriter.h \
		/usr/local/Qt-5.0.2/include/QtGui/qabstracttextdocumentlayout.h \
		/usr/local/Qt-5.0.2/include/QtGui/qtextlayout.h \
		/usr/local/Qt-5.0.2/include/QtGui/qtextformat.h \
		/usr/local/Qt-5.0.2/include/QtGui/qglyphrun.h \
		/usr/local/Qt-5.0.2/include/QtGui/qrawfont.h \
		/usr/local/Qt-5.0.2/include/QtGui/qfontdatabase.h \
		/usr/local/Qt-5.0.2/include/QtGui/qtextcursor.h \
		/usr/local/Qt-5.0.2/include/QtGui/qtextdocument.h \
		/usr/local/Qt-5.0.2/include/QtGui/qstatictext.h \
		/usr/local/Qt-5.0.2/include/QtGui/qsyntaxhighlighter.h \
		/usr/local/Qt-5.0.2/include/QtGui/qtextobject.h \
		/usr/local/Qt-5.0.2/include/QtGui/qtextdocumentfragment.h \
		/usr/local/Qt-5.0.2/include/QtGui/qtextdocumentwriter.h \
		/usr/local/Qt-5.0.2/include/QtGui/qtextlist.h \
		/usr/local/Qt-5.0.2/include/QtGui/qtexttable.h \
		/usr/local/Qt-5.0.2/include/QtGui/qdesktopservices.h \
		/usr/local/Qt-5.0.2/include/QtGui/qvalidator.h \
		/usr/local/Qt-5.0.2/include/QtGui/QGenericPluginFactory \
		/usr/local/Qt-5.0.2/include/QtGui/QGenericPlugin \
		/usr/local/Qt-5.0.2/include/QtGui/qtguiversion.h \
		/usr/local/Qt-5.0.2/include/QtWidgets/QApplication \
		/usr/local/Qt-5.0.2/include/QtWidgets/qapplication.h \
		/usr/local/Qt-5.0.2/include/QtWidgets/qdesktopwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

