######################################################################
# Automatically generated by qmake (2.01a) sob. maj 25 11:24:49 2013
######################################################################

QT += testlib gui widgets

CONFIG+=testcase
TEMPLATE = app
TARGET = test
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dpfile.h dpdir.h utils.h taskprogress.h taskprogressmanager.h mainwindow.h dptest.h
FORMS += mainwindow.ui
SOURCES += dpfile.cpp dpdir.cpp utils.cpp taskprogress.cpp taskprogressmanager.cpp mainwindow.cpp dptest.cpp



HEADERS  += dpfile.h \
            dpdir.h \
            err.h \
            utils.h \
            taskprogress.h \
            taskprogressmanager.h \
            mainwindow.h

